---
title: "ОТЧЕТ
О ВОЗМОЖНЫХ ЗАТРАТАХ НА ЗАПУСК ПРОМЫШЛЕННОГО ПРОИЗВОДСТВА В ГОРОДЕ МОСКВЕ"
output:
  word_document:
    reference_docx: report_reverence.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ПРИВЕТСТВЕННОЕ СЛОВО

Спасибо, что воспользовались электронным сервисом\
«Инвестиционный калькулятор города Москвы»!\
Мы надеемся, что предоставленная возможность предварительного расчета расходов на содержание персонала организации, размещение промышленных объектов на территории города Москвы, а также необходимые регистрационные и прочие услуги была полезна для Вас.\
Сегодня Москва является ведущим промышленным регионом России, где работает более 3 500 производственных предприятий, продукция которых экспортируется в 186 стран мира. Правительство Москвы предоставляет более 150 мер государственной поддержки промышленным организациям, с которыми можно подробно ознакомиться и подать соответствующую заявку в специализированном разделе Инвестиционного портала города Москвы.\
Вы также можете получить льготные условия для ведения промышленной деятельности, получив статус резидента особой экономической зоны «Технополис Москва».\
Мы убеждены, что вместе с Вами сможем открыть новые горизонты современной отечественной промышленности!

##### ОБЗОР ПРЕДВАРИТЕЛЬНЫХ РАСХОДОВ

# ИНФОРМАЦИЯ О ВАШЕЙ ОРГАНИЗАЦИИ
#### ОТРАСЛЬ: Авиационная промышленность
#### ТИП ОРГАНИЗАЦИИ: ИП
#### КОЛИЧЕСТВО СОТРУДНИКОВ: 150 человек
#### РАЙОН РАСПОЛОЖЕНИЯ ПРОИЗВОДСТВА: Троицкий округ
#### 
#### 
#### 

# ИТОГОВЫЕ ЗНАЧЕНИЯ ВОЗМОЖНЫХ ЗАТРАТ
#### ИТОГО ВОЗМОЖНЫХ РАСХОДОВ: от 517.9 до 715 млн.руб
#### ПЕРСОНАЛ: от 169.5 до 204.3 млн.руб
#### АРЕНДА: от 320 до 480 млн.руб
#### НАЛОГИ: от 25.8 до 28.2 млн.руб
#### УСЛУГИ: 0.2 млн.руб
#### 
#### 
#### 
#### 
#### 
#### 


##### ОБЗОР ПРЕДВАРИТЕЛЬНЫХ РАСХОДОВ

# ПЕРСОНАЛ ОРГАНИЗАЦИИ
#### Москва является лидирующим регионом Российской Федерации с наибольшим количеством экономически активного населения.Уровень безработицы в столице – один из самых низких по стране и составляет менее 1%. Специалисты многих направлений заняты в самых разных областях деятельности: автомобилестроение, пищевая промышленность, приборостроение, станкоинструментальная промышленность, легкая промышленность и другие. Правительство Москвы способствует развитию новых специальностей и компетенций.Благодаря проекту «Московская техническая школа» Вы можете подать заявку на обучение своих сотрудников необходимым профессиональным навыкам.

#### 
#### 
#### 

#### ИТОГО ВОЗМОЖНЫХ РАСХОДОВ НА СОДЕРЖАНИЕ ПЕРСОНАЛА ОРГАНИЗАЦИИ: от 169.5 до 204.3 млн.руб
#### ПЛАНИРУЕМАЯ ЧИСЛЕННОСТЬ ПЕРСОНАЛА:150 человек
#### СТРАХОВЫЕ ВЗНОСЫ (ПЕНСИОННОЕ СТРАХОВАНИЕ): от 9.4 до 34.6 млн.руб
#### СТРАХОВЫЕ ВЗНОСЫ (МЕДИЦИНСКОЕ СТРАХОВАНИЕ): от 0.2 до 8 млн.руб
#### 
#### 

##### ОБЗОР ПРЕДВАРИТЕЛЬНЫХ РАСХОДОВ

# АРЕНДА
#### В 2020 году на рынке аренды коммерческих помещений в Москве наблюдался спад из-за пандемии COVID-19 и ограничений, связанных с карантином. Средняя цена аренды офисных помещений в Москве снизилась на 10-15%, а цены на аренду торговых помещений упали на 20-30%. Однако, в 2021 году наблюдается постепенное восстановление рынка аренды коммерческих помещений в Москве. Согласно отчетам, цены на аренду офисных помещений в Москве в первом квартале 2021 года выросли на 1,5-2%, а цены на аренду торговых помещений остались на уровне 2020 года. В целом, рынок аренды коммерческих помещений в Москве остается одним из самых дорогих и перспективных в России.

#### 
#### 
#### 

#### ИТОГО ВОЗМОЖНЫХ РАСХОДОВ НА АРЕНДУ ПОМОЩЕНИЙ:  от 320 до 480 млн.руб
#### В том числе:Жилые здания

#### 
#### 
#### 
#### 
#### 
#### 
#### 

##### ОБЗОР ПРЕДВАРИТЕЛЬНЫХ РАСХОДОВ

# НАЛОГОВЫЕ ОТЧИСЛЕНИЯ
#### В 2021 году в Москве введены новые налоговые льготы для предпринимателей, направленные на поддержку малого и среднего бизнеса. В частности, с 1 января 2021 года введена льгота по налогу на имущество для предприятий, занимающихся производством товаров на территории Москвы. Также введены льготы по налогу на прибыль для предприятий, осуществляющих инвестиционную деятельность в Москве. В целом, Москва является одним из наиболее благоприятных регионов для создания и развития бизнеса в России, благодаря высокому уровню инфраструктуры, доступности квалифицированных кадров и наличию различных налоговых льгот для предпринимателей.

#### 
#### 
#### 
#### 

#### ИТОГО ВОЗМОЖНЫХ РАСХОДОВ НА НАЛОГОВЫЕ ОТЧИСЛЕНИЯ:  от 25.8 до 28.2 млн.руб

#### 
#### 
#### 
#### 
####

##### ОБЗОР ПРЕДВАРИТЕЛЬНЫХ РАСХОДОВ

# УСЛУГИ
#### Москва предоставляет ряд преимуществ и услуг для бизнеса при создании предприятия. В частности, в Москве действует единое окно для предоставления государственных и муниципальных услуг, что упрощает процедуру регистрации и создания предприятия. Также в Москве действует программа поддержки малого и среднего бизнеса, которая включает в себя финансовую поддержку, консультации и обучение предпринимателей. В 2021 году в Москве введены новые меры поддержки бизнеса, направленные на снижение административных барьеров и упрощение процедур. В частности, введена услуга по выдаче электронных сертификатов для предпринимателей, что позволяет сократить время на получение разрешительной документации.

#### 
#### 
#### 
#### 

#### ИТОГО ВОЗМОЖНЫХ РАСХОДОВ НА УСЛУГИ: 0.2 млн.руб

#### 
#### 
####
#### 
####
####

##### ОБЗОР РЕСУРСОВ

# ОБЩЕЕ ОПИСАНИЕ
#### В Москве промышленным организациям предоставляется адресная государственная поддержка в рамках программы "Развитие промышленности и повышение ее конкурентоспособности в городе Москве". В рамках этой программы предприятиям предоставляются субсидии на развитие производства, модернизацию оборудования, повышение квалификации персонала и другие меры поддержки.В 2021 году на реализацию программы "Развитие промышленности и повышение ее конкурентоспособности в городе Москве" выделено более 5 миллиардов рублей. В рамках этой программы планируется поддержать более 200 промышленных предприятий в Москве. В целом, адресная государственная поддержка промышленным организациям в Москве является одной из важных мер поддержки бизнеса и способствует развитию промышленности в городе.

#### 
#### 
#### 
#### 

[Инвестиционный портала города Москвы](https://investmoscow.ru/online-services/navigator-support-measures)\
[Технополис Москва](https://technomoscow.ru/)\
[Московская техническая школа](http://moscowtechschool.ru/)

#### 

##### ЗАКЛЮЧЕНИЕ

# ЗАКЛЮЧИТЕЛЬНОЕ СЛОВО
#### В заключение, инвестирование в промышленное предприятие в городе Москва является перспективным и выгодным решением для бизнеса. Благодаря высокому уровню инфраструктуры, доступности квалифицированных кадров и наличию различных программ поддержки, Москва предоставляет отличные условия для развития промышленности и бизнеса в целом. Инвестирование в промышленное предприятие в Москве может стать успешным и долгосрочным проектом, который принесет высокую доходность и укрепит позиции бизнеса на рынке.