---
title: "ОТЧЕТ
О ВОЗМОЖНЫХ ЗАТРАТАХ НА ЗАПУСК ПРОМЫШЛЕННОГО ПРОИЗВОДСТВА В ГОРОДЕ МОСКВЕ"
output:
  word_document:
    reference_docx: report_reverence.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ПРИВЕТСТВЕННОЕ СЛОВО

Спасибо, что воспользовались электронным сервисом\
«Инвестиционный калькулятор города Москвы»!\
Мы надеемся, что предоставленная возможность предварительного расчета расходов на содержание персонала организации, размещение промышленных объектов на территории города Москвы, а также необходимые регистрационные и прочие услуги была полезна для Вас.\
Сегодня Москва является ведущим промышленным регионом России, где работает более 3 500 производственных предприятий, продукция которых экспортируется в 186 стран мира. Правительство Москвы предоставляет более 150 мер государственной поддержки промышленным организациям, с которыми можно подробно ознакомиться и подать соответствующую заявку в специализированном разделе Инвестиционного портала города Москвы.\
Вы также можете получить льготные условия для ведения промышленной деятельности, получив статус резидента особой экономической зоны «Технополис Москва».\
Мы убеждены, что вместе с Вами сможем открыть новые горизонты современной отечественной промышленности!

##### ОБЗОР ПРЕДВАРИТЕЛЬНЫХ РАСХОДОВ

# ИНФОРМАЦИЯ О ВАШЕЙ ОРГАНИЗАЦИИ
#### ОТРАСЛЬ: Вставить сюда
#### ТИП ОРГАНИЗАЦИИ: Вставить сюда
#### КОЛИЧЕСТВО СОТРУДНИКОВ: Вставить сюда
#### РАЙОН РАСПОЛОЖЕНИЯ ПРОИЗВОДСТВА: Вставить сюда
#### 
#### 
#### 

# ИТОГОВЫЕ ЗНАЧЕНИЯ ВОЗМОЖНЫХ ЗАТРАТ
#### ИТОГО ВОЗМОЖНЫХ РАСХОДОВ: Вставить сюда
#### ПЕРСОНАЛ: Вставить сюда
#### АРЕНДА : Вставить сюда
#### НАЛОГИ: Вставить сюда
#### УСЛУГИ: Вставить сюда
#### 
#### 
#### 
#### 
#### 
#### 


##### ОБЗОР ПРЕДВАРИТЕЛЬНЫХ РАСХОДОВ

# ПЕРСОНАЛ ОРГАНИЗАЦИИ
#### Москва является лидирующим регионом Российской Федерации с наибольшим количеством экономически активного населения.Уровень безработицы в столице – один из самых низких по стране и составляет менее 1%. Специалисты многих направлений заняты в самых разных областях деятельности: автомобилестроение, пищевая промышленность, приборостроение, станкоинструментальная промышленность, легкая промышленность и другие. Правительство Москвы способствует развитию новых специальностей и компетенций.Благодаря проекту «Московская техническая школа» Вы можете подать заявку на обучение своих сотрудников необходимым профессиональным навыкам.

#### 
#### 
#### 

#### ИТОГО ВОЗМОЖНЫХ РАСХОДОВ НА СОДЕРЖАНИЕ ПЕРСОНАЛА ОРГАНИЗАЦИИ: Вставить сюда от до
#### ПЛАНИРУЕМАЯ ЧИСЛЕННОСТЬ ПЕРСОНАЛА: Вставить сюда
#### СТРАХОВЫЕ ВЗНОСЫ (ПЕНСИОННОЕ СТРАХОВАНИЕ) : Вставить сюда
#### СТРАХОВЫЕ ВЗНОСЫ (МЕДИЦИНСКОЕ СТРАХОВАНИЕ): Вставить сюда